# Generated by Django 4.2.13 on 2024-08-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('rg_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
