# Generated by Django 4.2.13 on 2024-09-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='rg_number',
            new_name='rg',
        ),
        migrations.AddField(
            model_name='passenger',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
