# Generated by Django 4.2.13 on 2024-08-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='approved_by_crew',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SeatReservation',
        ),
    ]
