# Generated by Django 4.2.13 on 2024-08-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_arrival_time_flight_return_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='approval_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Rejeitado')], default='P', max_length=1),
        ),
    ]
