# Generated by Django 4.2.13 on 2024-08-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_passenger_flightpassenger_flight_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='passengers',
        ),
        migrations.DeleteModel(
            name='FlightPassenger',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
