# Generated by Django 4.2.13 on 2024-08-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_flights', models.IntegerField()),
                ('total_hours_flown', models.FloatField()),
                ('average_occupancy_rate', models.FloatField()),
            ],
        ),
    ]
